# Outputs
output "user-wp-developer" {
  value = "User ${aws_iam_user.wp-developer.id} has no login profile nor access key generated by terraform for security. You may create the credential via AWS CLI or AWS console."
}